name: Weather app CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          user: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}   
        run: |
          docker login -u $user -p $password
      - name: Docker build image
        run: docker build . -t npsoni/weatherapp
      - name: Docker push
        run: docker push npsoni/weatherapp
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: kubectl apply -f kubernetes-resources/deployment.yaml
